#!/bin/bash

set -e

base_profile="v2.1"
copy_profiles="v3.2-core" # TODO(dmac) Support more profiles
cwd=`pwd`
for p in $copy_profiles; do
  rm -fr $p
  cp -r $base_profile $p
  cd $p/gg
  for f in `ls`; do
    echo '// Code generated by generate.sh' >> $f.new
    echo '// Do not edit!' >> $f.new
    echo '' >> $f.new
    sed -e "s:\"github.com/go-gl/gl/$base_profile/gl\":\"github.com/go-gl/gl/$p/gl\":" $f >> $f.new
    mv $f.new $f
  done
  cd $cwd/testdata
  rm -fr $p
  cp -r $base_profile $p
  cd $p
  for f in `ls`; do
    echo '// Code generated by generate.sh' >> $f.new
    echo '// Do not edit!' >> $f.new
    echo '' >> $f.new
    sed -e "s:$base_profile:$p:" $f >> $f.new
    mv $f.new $f
  done
done
